name: e2e test w/ Percy
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cypress-percy-visual-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
      - name: Install dependencies
        run: npm install

      - name: Cypress visual tests 🧪
        uses: cypress-io/github-action@v4.2.2
        with:
          install: false
          start: npm run serve # builds and subsequently runs the development server
          wait-on: 'http://localhost:8000/'
          browser: chrome
          command: npx percy exec -- npm run cypress:headless
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}